### ISSUE TITLE
Polymer Structure

### ISSUE THREAD

**Issue by qbKhanh** [Augus1999/mol2chemfigPy3#2]
Can your open-source translate Polymer Structure in SMILES string into Chemfig?
![image](https://github.com/Augus1999/mol2chemfigPy3/assets/90884691/9ca87f6d-1301-4fd7-9dbc-794f69835881)

Thanks for considering!

**Comment by Augus1999** [comment]
Mol2chemfig uses `epam.indigo` as the backend, and unfortunately it doesn't support customised SMILES versions (e.g., [BigSMILES](https://olsenlab.mit.edu/research/bigsmiles/) and [Polymer Genome SMILES](https://www.polymergenome.org/guide#:~:text=A%20SMILES%20string%20used%20for%20Polymer%20Genome%20represents,ends%20at%20the%20last%20atom%20of%20the%20string.)) which support polymer structure.

I think you can consider using the `-g` flag to annotate atoms, then manually convert the code to polymer style. Here is an example:
1. consider the first structure in your image
2. use the SMILES without dangling bonds `C=CC=CC=C`
3. convert to chemfig code with `-g` flag: `mol2chemfig -wo -g a -i direct "C=CC=CC=C"`
4. then you will get:
```latex
\chemfig{
                  @{a1}%
    =[@{a1-2}:330]@{a2}%
     -[@{a2-3}:30]@{a3}%
    =[@{a3-4}:330]@{a4}%
     -[@{a4-5}:30]@{a5}%
    =[@{a5-6}:330]@{a6}%
}
```
5. manually add the dangling bonds at atom 1 and atom 6:
```latex
\chemfig{
                 [:30]-%add dangling bond!
                  @{a1}%
    =[@{a1-2}:330]@{a2}%
     -[@{a2-3}:30]@{a3}%
    =[@{a3-4}:330]@{a4}%
     -[@{a4-5}:30]@{a5}%
    =[@{a5-6}:330]@{a6}%
                      -%add dangling bond!
}
```
6. type into latex (see [reference](https://tex.stackexchange.com/questions/188615/how-i-can-write-polymeric-reaction-in-latex)) as:
```latex
\documentclass[12pt,leqno]{article}
\usepackage[utf8]{inputenc}
\usepackage{mol2chemfig}
\usepackage{chemfig}
\usepackage{chemformula}

% polymer delimiters:
\makeatletter
\newcommand*\setpolymerdelim[2]{\def\polymer@delimleft{#1}\def\polymer@delimright{#2}}

\newcommand*\makepolymerbraces[5]{%
	\edef\polymer@delimhalfdim{\the\dimexpr(#1+#2)/2}%
	\edef\polymer@delimvshift{\the\dimexpr(#1-#2)/2}%
	\chemmove{
		\node[at=(#4),yshift=(\polymer@delimvshift)]
		{$
			\left\polymer@delimleft
			\vrule height\polymer@delimhalfdim depth\polymer@delimhalfdim width0pt
			\right.
			$};
		\node[at=(#5),yshift=(\polymer@delimvshift)]
		{$
			\left.
			\vrule height\polymer@delimhalfdim depth\polymer@delimhalfdim width0pt
			\right\polymer@delimright_{\rlap{#3}}
			$};
	}%
}
\makeatother


\begin{document}
	
	
	\begin{equation}
		\setpolymerdelim[]%\setatomsep{2em}
		\schemestart
		$x$
		\chemfig{
			[:30]-%add dangling bond!
			@{a1}%
			=[@{a1-2}:330]@{a2}%
			-[@{a2-3}:30]@{a3}%
			=[@{a3-4}:330]@{a4}%
			-[@{a4-5}:30]@{a5}%
			=[@{a5-6}:330]@{a6}%
			-%add dangling bond
		}
		\schemestop
		\makepolymerbraces{30pt}{30pt}{$n$}{a1}{a6}
	\end{equation}
	
\end{document}
```
7. then you get 
<img width="239" alt="スクリーンショット 2023-12-22 171134" src="https://github.com/Augus1999/mol2chemfigPy3/assets/39725660/8c437b4a-13b4-4480-82af-9be24ca3d811">

Hope this helps you.

**Comment by qbKhanh** [comment]
Thank for your quick reply!

Your help is a big suggestion! I will try follow this way.

TA!
