### ISSUE TITLE
Save to txt file

### ISSUE THREAD

**Issue by Martin-2019** [Augus1999/mol2chemfigPy3#3]
Dear Author!

The question, or request for a new function, is as follows: how to save the result of an action to a file, e.g. txt with this code:

mol2chemfig -zw -i direct "C1=CC=C(C=C1)O"

inside latex file or inside python code:

\begin{python}
from mol2chemfigPy3 import mol2chemfig

mol2chemfig('996')  # search the PubChem database

mol2chemfig('C1=CC=C(C=C1)O')  # transfer InChI/SMILES to chemfig # this part is especially interesting

\end{python}

inside latex file ?

Thank You in advance!

**Comment by Augus1999** [comment]
Hello, you can always redirect the output from stdout to a file, e.g.,
```bash
mol2chemfig -zw -i direct "C1=CC=C(C=C1)O" > phenol.tex
```
writes the result to the file `phenol.tex`.

Let me know if you have any other questions.

**Comment by Martin-2019** [comment]
The question is inside attached file.

I would like to generate \chemfig{…} with python inside a python block, and use in next part my file, as \include{…} or \input{…}



Thank You in advance.


M

￼

**Comment by Augus1999** [comment]
Now I think it's rather a question about how to get access to python variables inside LaTex code. I suggest referring to https://tex.stackexchange.com/questions/33129/using-python-within-latex-and-accessing-its-variables, although it seems to have no simple solutions.

**Comment by Augus1999** [comment]
There is no reply for a fortnight, so I think this issue can be thought as solved.
